site_name: RELOG
theme: cinder
copyright: "Copyright © 2020, UChicago Argonne, LLC. All Rights Reserved."
repo_url: https://github.com/ANL-CEEESA/RELOG
edit_uri: edit/master/src/docs/
nav:
    - Home: index.md
    - Usage: usage.md
    - Data Format: format.md
    - Reports: reports.md
    - Optimization Model: model.md
plugins:
  - search
markdown_extensions:
  - admonition  
  - mdx_math  
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - js/mathjax.js
docs_dir: src/docs
site_dir: docs
extra_css:
    - "css/custom.css"
